lb:
   image: eeacms/haproxy
   ports:
      - "80:80"
      - "1936:1936"
   links:
      - web

web:
   build: nodedemo
   ports: 
      - "80" 
   links:
      - db:contactdb

db:
   build: mongodbdir
   expose: 
      - 27017
   
