version: '2'

services:
#  lb:
#   image: eeacms/haproxy
#   ports:
#      - "80:5000"
#      - "1936:1936"
#   links:
#      - webapp

  webapp:
   build: nodedemo
#   expose: 
#     - 80
   ports:
      - "80:80"
   links:
      - contactdb

  contactdb:
   image: mongo
   volumes:
      - ./mongodata:/data/db
   expose: 
      - 27017
   
